algo = input('Digite algo: ')
print('O tipo primitivo desse valor é :' , type(algo))
print('Só tem espaços?', algo.isspace())
print('É um número?', algo.isnumeric())
print('É alfabetico?',algo.isalpha())
print('É alfanumérico?',algo.isalnum())
print('É tudo maiusculo?',algo.isupper())
print('É tudo minusculo?',algo.islower())
print('Esta captalizada?', algo.istitle())